name: <WORKSPACE> test

on:
  push:
    branches: ["<WORKSPACE>"]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: <WORKSPACE>
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "<TEST_TASK_NAME>"
        run: touch .env
          && rm .env
          && touch .env
          && yarn install && yarn test
