name: <WORKSPACE> build and Push

on:
  push:
    branches: ["<WORKSPACE>"]

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    environment: <WORKSPACE>
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "auth"
        uses: "google-github-actions/auth@v2"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Apply env"
        run: touch .env
          && rm .env
          && touch .env

      - name: Build image
        run: docker build . --file ./Dockerfile --tag
        working-directory: ./

      - name: Push image
        run: docker push

      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: /build/apply
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
