name: staging test

on:
  push:
    branches: ["staging"]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Test"
        run: touch .env
          && rm .env
          && touch .env
          && echo WORKSPACE=${{ secrets.WORKSPACE }} >> .env
          && echo ref_name=${{ github.ref_name }} >> .env
          && echo TEST=${{ vars.TEST }} >> .env
          && yarn install && yarn test
