name: staging build and Push to Artifact Registry GAR

on:
  push:
    branches: ["staging"]

env:
  REGION: ${{ secrets.REGION }}
  GAR_LOCATION: ${{ vars.GAR_LOCATION }}/mmp/${{ github.ref_name }}

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCLOUD_SERVICE_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "Apply env"
        run: touch .env
          && rm .env
          && touch .env
          && echo WORKSPACE=${{ secrets.WORKSPACE }} >> .env
          && echo TEST=${{ secrets.TEST }} >> .env
      - name: Build image
        run: docker build . --file ./Dockerfile --tag ${{ env.GAR_LOCATION }}
        working-directory: ./
      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_URL }}/build/apply
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"id": ${{ vars.BUILD_ID }},"buildId": "${{ github.sha }}","key":"${{ secrets.BUILD_KEY }}"}'
